package com.codecanvas.paymentservice.entity;

import com.codecanvas.paymentservice.enums.Currency;
import com.codecanvas.paymentservice.enums.PaymentStatus;
import com.codecanvas.paymentservice.enums.WebhookProcessingStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(
        name = "payments",
        indexes = {
                @Index(name = "idx_payment_user", columnList = "user_id"),
                @Index(name = "idx_payment_status", columnList = "payment_status"),
                @Index(name = "idx_payment_order", columnList = "razorpay_order_id"),
                @Index(name = "idx_payment_payment", columnList = "razorpay_payment_id"),
                @Index(name = "idx_payment_created", columnList = "created_at")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "payment_id", nullable = false, updatable = false)
    private UUID paymentId;

    /**
     * User who initiated the payment.
     */
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    /**
     * Purchased subscription plan ID.
     */
    @Column(name = "plan_id", nullable = false)
    private Long planId;

    /**
     * Snapshot of the plan name at the time of payment.
     * This avoids additional Feign calls while displaying payment history.
     */
    @Column(name = "plan_name", nullable = false)
    private String planName;

    /**
     * Payment amount.
     */
    @Column(name = "amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    /**
     * Payment currency.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "currency", nullable = false, length = 10)
    @Builder.Default
    private Currency currency = Currency.INR;

    /**
     * Current payment status.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false)
    @Builder.Default
    private PaymentStatus paymentStatus = PaymentStatus.CREATED;

    /**
     //     * Refund status.
     //     */
//    @Enumerated(EnumType.STRING)
//    @Column(name = "refund_status", nullable = false)
//    @Builder.Default
//    private RefundStatus refundStatus = RefundStatus.NOT_REFUNDED;

    /**
     * Webhook processing state.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "webhook_status", nullable = false)
    @Builder.Default
    private WebhookProcessingStatus webhookProcessingStatus =
            WebhookProcessingStatus.NOT_RECEIVED;

    /**
     * Razorpay Order ID.
     */
    @Column(name = "razorpay_order_id", unique = true)
    private String razorpayOrderId;

    /**
     * Razorpay Payment ID.
     */
    @Column(name = "razorpay_payment_id", unique = true)
    private String razorpayPaymentId;

    /**
     * Razorpay payment signature received after successful payment.
     */
    @Column(name = "razorpay_signature")
    private String razorpaySignature;

    /**
     * UPI, CARD, NETBANKING, WALLET, etc.
     */
    @Column(name = "payment_method")
    private String paymentMethod;

    /**
     * Failure reason in case payment fails.
     */
    @Column(name = "failure_reason", columnDefinition = "TEXT")
    private String failureReason;

    /**
     * Internal receipt generated by CodeCanvas.
     */
    @Column(name = "receipt", nullable = false, unique = true)
    private String receipt;

    /**
     * Optional notes.
     */
    @Column(name = "notes", columnDefinition = "TEXT")
    private String notes;

    /**
     * Payment completion timestamp.
     */
    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    /**
     * Entity creation timestamp.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Entity update timestamp.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @PrePersist
    public void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    public void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}