package com.codecanvas.paymentservice.dto.response;

import lombok.*;

import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RazorpayOrderResponse {

    /**
     * Internal Payment ID
     */
    private UUID paymentId;

    /**
     * Razorpay Order ID
     */
    private String razorpayOrderId;

    /**
     * Razorpay Key ID
     * Required by frontend to initialize Razorpay Checkout
     */
    private String razorpayKey;

    /**
     * Amount in paise
     * Example:
     * ₹499.00 -> 49900
     */
    private Long amount;

    /**
     * Currency
     * Example: INR
     */
    private String currency;

    /**
     * Receipt generated by our application
     */
    private String receipt;
}