server:
  port: 8082

spring:
  application:
    name: snippet-service

  datasource:
    url: jdbc:postgresql://localhost:5432/codecanvas
    username: postgres
    password: Yash@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cache:
    type: redis
    redis:
      time-to-live: 600000
      use-key-prefix: true
      key-prefix: "snippet-service::"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:3600000}


cloudinary:
  cloud-name: wqxaugxx
  api-key: 916333465954846
  api-secret: O3wWyyinEI4MWawHlxuj3mrJtaY